const SHOP_DATA = {
    headphones: {
        id: 1,
        title: 'Headphones',
        routeName: 'headphones',
        items: [{
                id: 1,
                name: 'Dre Beats',
                imageUrl: `https://i.ibb.co/PZ3tkJF/HP1.jpg`,
                price: 225,
            },
            {
                id: 2,
                name: 'Beats by Dre',
                imageUrl: `https://i.ibb.co/0FGPncF/HP2.jpg `,
                price: 338,
            },
            {
                id: 3,
                name: 'Prestige',
                imageUrl: `https://i.ibb.co/GkNJjn9/HP3.jpg `,
                price: 135,
            },
            {
                id: 4,
                name: 'Yell-Ow',
                imageUrl: `https://i.ibb.co/DtbZRvq/HP4.jpg `,
                price: 125,
            },
            {
                id: 5,
                name: 'Sony',
                imageUrl: `https://i.ibb.co/NCP7hS4/HP5.jpg `,
                price: 58,
            },
            {
                id: 6,
                name: 'Red Sony',
                imageUrl: `https://i.ibb.co/v1Vy4vz/HP6.jpg`,
                price: 224,
            },
            {
                id: 7,
                name: 'Amazon',
                imageUrl: `https://i.ibb.co/1zgsSZK/HP7.jpg `,
                price: 108,
            },
            {
                id: 8,
                name: 'Grey',
                imageUrl: `https://i.ibb.co/0Jg2Z43/HP8.jpg `,
                price: 494,
            },
            {
                id: 9,
                name: 'Air Pods',
                imageUrl: `https://i.ibb.co/SPm6jBx/aboutBcg.jpg `,
                price: 16,
            },
        ],
    },
    laptops: {
        id: 2,
        title: 'Laptops',
        routeName: 'laptops',
        items: [{
                id: 10,
                name: 'Macbook',
                imageUrl: `https://i.ibb.co/sqNV26m/LP7.jpg`,
                price: 11220,
            },
            {
                id: 11,
                name: 'Macbook pro',
                imageUrl: `https://i.ibb.co/qYTdRfM/LP6.jpg`,
                price: 12280,
            },
            {
                id: 12,
                name: 'Samsung',
                imageUrl: `https://i.ibb.co/yd2LXVm/LP5.jpg`,
                price: 710,
            },
            {
                id: 13,
                name: 'Dell',
                imageUrl: `https://i.ibb.co/FwB5wtC/LP3.jpg`,
                price: 560,
            },
            {
                id: 14,
                name: 'Lenovo',
                imageUrl: `https://i.ibb.co/nMQSxSJ/LP1.jpg`,
                price: 460,
            },
            {
                id: 15,
                name: 'Acer',
                imageUrl: `https://i.ibb.co/bmdG2d7/LP4.jpg`,
                price: 360,
            },
            {
                id: 16,
                name: 'Google',
                imageUrl: `https://i.ibb.co/nntvDMc/LP2.jpg`,
                price: 190,
            },
            {
                id: 17,
                name: 'HP',
                imageUrl: `https://i.ibb.co/qYTdRfM/LP6.jpg`,
                price: 200,
            },
        ],
    },
    phones: {
        id: 3,
        title: 'Phones',
        routeName: 'phones',
        items: [{
                id: 18,
                name: 'Iphne',
                imageUrl: `https://i.ibb.co/VBHhJg6/phone1.jpg `,
                price: 125,
            },
            {
                id: 19,
                name: 'Iphone3 ',
                imageUrl: `https://i.ibb.co/sqT9WG1/phone5.jpg `,
                price: 90,
            },
            {
                id: 20,
                name: 'Samsung',
                imageUrl: `https://i.ibb.co/jJC76HM/phone3.jpg `,
                price: 90,
            },
            {
                id: 21,
                name: 'Huwaie',
                imageUrl: `https://i.ibb.co/Z6NBhKg/phone4.jpg `,
                price: 165,
            },
            {
                id: 22,
                name: 'Nokia',
                imageUrl: `https://i.ibb.co/nMNtNWw/phone6.jpg `,
                price: 185,
            },
        ],
    },
    speakers: {
        id: 4,
        title: 'Speakers',
        routeName: 'speakers',
        items: [{
                id: 23,
                name: 'Grundig',
                imageUrl: `https://i.ibb.co/JF2GKHs/speaker1.jpg `,
                price: 25,
            },
            {
                id: 24,
                name: 'Provex',
                imageUrl: `https://i.ibb.co/25XhcFy/speaker7.jpg `,
                price: 20,
            },
            {
                id: 25,
                name: 'Amazon',
                imageUrl: `https://i.ibb.co/Ntn6Fsb/speaker9.jpg`,
                price: 80,
            },
            {
                id: 26,
                name: 'Google',
                imageUrl: `https://i.ibb.co/k1zWxXJ/speaker4.jpg `,
                price: 80,
            },
            {
                id: 27,
                name: 'Bose',
                imageUrl: `https://i.ibb.co/W3Nm0rf/speaker11.jpg `,
                price: 45,
            },
            {
                id: 28,
                name: 'Bluapunkt',
                imageUrl: `https://i.ibb.co/qD3gXFn/speaker12.jpg `,
                price: 135,
            },
            {
                id: 29,
                name: 'Ramikic',
                imageUrl: `https://i.ibb.co/CWZdxLc/speaker8.jpg `,
                price: 20,
            },
        ],
    },
    tv: {
        id: 5,
        title: 'Tv',
        routeName: 'tv',
        items: [{
                id: 30,
                name: 'Sony',
                imageUrl: `https://i.ibb.co/WfDr0xm/tv6.jpg `,
                price: 1325,
            },
            {
                id: 31,
                name: 'Panasonic',
                imageUrl: `https://i.ibb.co/0Xx5N68/tv5.jpg `,
                price: 920,
            },
            {
                id: 32,
                name: 'Samsung',
                imageUrl: `https://i.ibb.co/r7MsyxW/tv4.jpg `,
                price: 2525,
            },
            {
                id: 33,
                name: 'LG',
                imageUrl: `https://i.ibb.co/y4XXWNh/tv3.jpg`,
                price: 1125,
            },
            {
                id: 34,
                name: 'Sharp',
                imageUrl: `https://i.ibb.co/RPxvqXb/tv2.jpg `,
                price: 840,
            },
            {
                id: 35,
                name: 'Radical',
                imageUrl: `https://i.ibb.co/nntvDMc/LP2.jpg `,
                price: 625,
            },
        ],
    },
};

export default SHOP_DATA;